apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"nginx:v1.00"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nginx\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2023-06-11T10:31:28Z"
  generation: 3
  labels:
    app: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: nginx
  name: nginx
  namespace: devops-practice
  resourceVersion: "473560"
  uid: 5a545ded-9ebe-407d-b5fc-0f92026e4a84
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: nginx
    spec:
      containers:
      - image: docker.io/yahyaalshamrani/devops-practice@sha256:c0127fc7e9a89729f73d05410746d5e2520f840093d41a5475059017f447d766
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: app-sa
      serviceAccountName: app-sa
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-11T10:31:54Z"
    lastUpdateTime: "2023-06-11T10:31:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-11T10:31:28Z"
    lastUpdateTime: "2023-06-11T10:31:54Z"
    message: ReplicaSet "nginx-6d8546cc55" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
